# A simple substitutions file for nutmeg-parser that shows the
# format.
name: if-expressions
description: Rewrite if-statements into canonical form
passes:

  - name: Pass 0, handle ifnot/elseifnot
    downwards:

      - name: part/if
        match:
          self:
            name: part
            key: keyword
            value: if
        action:
          replaceValue:
            key: iftype
            with: if

      - name: part/elseif
        match:
          self:
            name: part
            key: keyword
            value: elseif
        action:
          replaceValue:
            key: iftype
            with: elseif

      - name: part/ifnot
        match:
          self:
            name: part
            key: keyword
            value: ifnot
        action:
          replaceValue:
            key: iftype
            with: if

      - name: part/elseifnot
        match:
          self:
            name: part
            key: keyword
            value: elseifnot
        action:
          replaceValue:
            key: iftype
            with: elseif

    upwards:
      - name: form->if
        match:
          self:
            name: form
          child:
            name: part
            key: iftype
            value: if
            siblingPosition: 0
        action:
          replaceName:
            with: if

      - name: add-else
        match:
          self:
            name: if
          child:
            name: part
            key: keyword
            value: else
            cmp: false
            siblingPosition: -1
        action:
          newNodeChild:
            name: part
            key: keyword
            value: else
            offset: 1
            length: 0

      - name: normalise-elseif
        match:
          self:
            name: if
          child:
            name: part
            key: iftype
            value: elseif
            siblingPosition: -3
        action:
          newNodeChild:
            name: if
            length: 3
        repeatOnSuccess: true

  - name: Pass 1, introduce ifnot
    downwards:
      - name: if-not
        match:
          self:
            name: if
          child:
            name: part
            key: keyword
            value: ifnot
            siblingPosition: 0
        action:
          replaceName:
            with: ifnot

      - name: elseif-not
        match:
          self:
            name: if
          child:
            name: part
            key: keyword
            value: elseifnot
            siblingPosition: 0
        action:
          replaceName:
            with: ifnot
