name: Rewrite qualifiers
passes:

  - name: Rewrite qualifiers
    singlePass: true

    downwards:
      - name: Rewrite qualifiers
        match:
          self:
            name: var
          child:
            name: id
        action:
          sequence:
            - childAction:
                replaceValue:
                  key: qualifier
                  with: var
            - replaceByChild: 0
        breakOnSuccess: true


      - name: Rewrite qualifiers
        match:
          self:
            name: val
          child:
            name: id
        action:
          sequence:
            - childAction:
                replaceValue:
                  key: qualifier
                  with: val
            - replaceByChild: 0
        breakOnSuccess: true

      - name: Rewrite qualifiers
        match:
          self:
            name: const
          child:
            name: id
        action:
          sequence:
            - childAction:
                replaceValue:
                  key: qualifier
                  with: const
            - replaceByChild: 0
        breakOnSuccess: true

      - name: Validate qualifiers
        match:
          self:
            name.regexp: 'var|val|const'
        action:
          fail: "Qualifier was not followed by an identifier"

