# A simple substitutions file for nutmeg-parser that shows the 
# format.
name: Simple Rewrite Example
description: A simple example of rewriting a parse tree
passes:

  - name: Pass 1
    downwards:
      - name: Rename form using keyword
        match:
          self:
            name: form
          child:
            name: part
            key: keyword
            siblingPosition: 0
        action:
          replaceName:
            src: child
            from: value

      - name: Rename parts to seq
        match:
          self:
            name: part 
        action:
          replaceName:
            with: seq

      - name: Parentheses to seq
        match:
          self:
            name: delimited
            key: kind
            value: parentheses
        action:
          replaceName:
            with: seq

      - name: Rename negation as seq and toggle sign of number
        match:
          self:
            name: operator
            key: name
            value: "-"
            count: 1
          child:
            name: number
        action:
          sequence:
          - replaceName:
              with: seq
          - childAction:
              rotateOption:
                key: sign
                values: ["+", "-"]

      - name: Change ':=' to bind (POP)
        match:
          self:
            name: operator
            key: name
            value: ":="
            count: 2
        action:
          replaceName:
            with: bind

      - name: Change '<-' to assign (POP)
        match:
          self:
            name: operator
            key: name
            value: "<-"
            count: 2
        action:
          replaceName:
            with: assign

      - name: Change '<--' to update (UCALL)
        match:
          self:
            name: operator
            key: name
            value: "<--"
            count: 2
        action:
          replaceName:
            with: update

    upwards:
      - name: Anotation Merge (Step 1)
        match:
          self:
            name: unit
          child:
            name: delimited
            key: kind
            value: brackets
          nextChild:
            name: delimited
            key: kind
            value: brackets
        action:
          sequence:
          - repeat:
              mergeChildWithNext: true
          - childAction:
              replaceName:
                with: seq

      - name: Annotation (Step 2)
        match:
          self:
            name: unit
          child:
            name: delimited
            key: kind
            value: brackets
          nextChild:
            name: def
        action:
          newNodeChildWithNext:
            name: annotation

      - name: Remove name option from seq derived from negation.
        match:
          self:
            name: seq
            key: name
            value: "-"
            count: 1
        action:
          removeOption:
            key: name

      - name: Elide sequence of length 1
        match:
          self:
            name: seq
            count: 1
        action:
          repeat:
            replaceByChild: 0

      - name: Inline nested sequences
        match:
          self:
            name: seq
          child:
            name: seq
        action:
          repeat:
            inlineChild: true

