name: switch
description: Canonize switch forms
passes:
  - name: Pass 1
    downwards:
      - name: Switch
        match:
          self:
            name: form
          child:
            name: part
            key: keyword
            value: switch
            siblingPosition: 0
        action:
          replaceName:
            with: switch

      - name: remove endcase
        match:
          self:
            name: switch
          child:
            name: part
            key: keyword
            value: endcase
        action:
          removeChild: true

      - name: mark else part as default
        match:
          parent:
            name: switch
          self:
            name: part
            key: keyword
            value: else
        action:
          replaceName:
            with: default

      - name: mark case and then parts
        match:
          parent:
            name: switch
          self:
            name: part
            key: keyword
            value.regexp: case|then
        action:
          replaceName:
            src: self
            from: value




