# A simple substitutions file for nutmeg-parser that shows the 
# format.
name: Simple Rewrite Example
description: A simple example of rewriting a parse tree
passes:

  - name: Pass 1
    downwards:
      - name: Insert else
        match:
          self:
            name: form
          child:
            name: part
            key: keyword
            value: else
            cmp: false
            siblingPosition: -1
        action:
          newNodeChild:
            name: part
            key: keyword
            value: else
            offset: 1
            length: 0

      - name: Undo cascade
        match:
          self:
            name: form
          child:
            name: part
            key: keyword
            value: elseif
            siblingPosition: -3
        action:
          sequence:
          - childAction:
              replaceValue:
                key: keyword
                with: if
          - newNodeChild:
              name: form
              length: 3

      - name: Flip ifnot
        match:
          self:
            name: form
            count: 3
          child:
            name: part
            key: keyword
            value: ifnot
            siblingPosition: 0
        action:
          sequence:
            - childAction:
                replaceValue:
                  key: keyword
                  with: if
            - permuteChildren: [1,2]
