# A simple substitutions file for nutmeg-parser that shows the 
# format.
name: if-expressions
description: Rewrite if-statements into canonical form
passes:

  - name: Pass 0, handle ifnot/elseifnot
    downwards:

      - name: ifnot
        match:
          self:
            name: part
            key: keyword
            value: ifnot
          child:
            siblingPosition: 0
        action:
          sequence:
            - replaceValue:
                key: keyword
                with: if
            - newNodeChild:
                name: not
                count: 1

      - name: elseifnot
        match:
          self:
            name: part
            key: keyword
            value: elseifnot
          child:
            siblingPosition: 0
        action:
          sequence:
            - replaceValue:
                key: keyword
                with: elseif
            - newNodeChild:
                name: not
                count: 1

        

      # - name: Mark forms
      #   match:
      #     self:
      #       name: form
      #     child:
      #       name: part
      #       key: keyword
      #       siblingPosition: 0
      #   action:
      #     replaceValue:
      #       key: keyword
      #       src: child
      #       from: value

      # - name: Insert else
      #   match:
      #     self:
      #       name: form
      #       key: keyword
      #       value: if
      #     child:
      #       name: part
      #       key: keyword
      #       value: else
      #       cmp: false
      #       siblingPosition: -1
      #   action:
      #     newNodeChild:
      #       name: part
      #       key: keyword
      #       value: else
      #       offset: 1
      #       length: 0

      # - name: Undo elseif
      #   match:
      #     self:
      #       name: form
      #       key: keyword
      #       value: if
      #     child:
      #       name: part
      #       key: keyword
      #       value: elseif
      #       siblingPosition: -3
      #   action:
      #     newNodeChild:
      #       name: form
      #       key: keyword
      #       value: quack
      #       length: 3
      #   # repeatOnSuccess: true

      # # - name: Flip ifnot
      # #   match:
      # #     self:
      # #       name: form
      # #       count: 3
      # #     child:
      # #       name: part
      # #       key: not
      # #       value: true
      # #       siblingPosition: 0
      # #   action:
      # #     sequence:
      # #       - childAction:
      # #           replaceValue:
      # #             key: not
      # #             with: false
      # #       - permuteChildren: [1,2]

    upwards:
      - name: form->quack
        match:
          self:
            name: form
          child:
            name: part
            key: keyword
            value: if
            siblingPosition: 0
        action:
          replaceName:
            key: keyword
            with: quack

      - name: add-else
        match:
          self:
            name: quack
          child:
            name: part
            key: keyword
            value: else
            cmp: false
            siblingPosition: -1
        action:
          newNodeChild:
            name: part
            key: keyword
            value: else
            offset: 1
            length: 0

      - name: Undo elseif
        match:
          self:
            name: quack
          child:
            name: part
            key: keyword
            value: elseif
            siblingPosition: -3
        action:
          newNodeChild:
            name: quack
            length: 3
        repeatOnSuccess: true