name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Test
      run: |
        go test ./...
        (cd functests && uv run python3 functest.py --quiet --tests */*.yaml)

  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: List dist directory
      run: ls -R dist/
    
    - name: Upload Linux binaries for Docker
      uses: actions/upload-artifact@v4
      with:
        name: nutmeg-binaries
        path: |
          dist/nutmeg-tokenizer_linux_amd64_v1/nutmeg-tokenizer
          dist/nutmeg-parser_linux_amd64_v1/nutmeg-parser
          dist/nutmeg-rewriter_linux_amd64_v1/nutmeg-rewriter
          dist/nutmeg-convert-tree_linux_amd64_v1/nutmeg-convert-tree
        retention-days: 1

  docker:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download binary artifacts
      uses: actions/download-artifact@v4
      with:
        name: nutmeg-binaries
        path: binaries
    
    - name: List downloaded artifacts
      run: ls -R binaries/
    
    - name: Move binaries to expected location
      run: |
        mkdir -p dist
        cp -r binaries/* dist/
        ls -R dist/
    
    - name: Extract tag name
      id: extract_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutmeg-tokenizer:${{ steps.extract_tag.outputs.tag }} .
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutmeg-tokenizer:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutmeg-tokenizer:${{ steps.extract_tag.outputs.tag }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutmeg-tokenizer:latest